# Generated by Django 3.0.8 on 2020-08-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='paradigm',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
