# Generated by Django 3.0.8 on 2020-08-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200813_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='user_email'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='', max_length=50, verbose_name='user_password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='username'),
        ),
    ]
