# Generated by Django 3.0.8 on 2020-08-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, unique=True, verbose_name='username')),
                ('user_password', models.CharField(default='', max_length=50, verbose_name='user_password')),
                ('user_email', models.CharField(default='', max_length=50, unique=True, verbose_name='user_email')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
