# Generated by Django 3.0.8 on 2020-09-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50, unique=True)),
            ],
        ),
    ]
