# Generated by Django 3.0.8 on 2020-08-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kouponbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50, unique=True, verbose_name='username')),
                ('user_password', models.CharField(default='', max_length=50, verbose_name='user_password')),
                ('user_email', models.CharField(default='', max_length=50, unique=True, verbose_name='user_email')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('picture', models.CharField(max_length=50)),
            ],
        ),
    ]
