# Generated by Django 3.0.8 on 2021-01-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kouponbank', '0002_auto_20210120_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='reservation',
        ),
    ]
