# Generated by Django 3.0.8 on 2020-10-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kouponbank', '0002_auto_20201010_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='isOwner',
        ),
    ]
