# Generated by Django 3.0.8 on 2021-01-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kouponbank', '0002_seat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
