# Generated by Django 3.0.8 on 2020-08-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kouponbank', '0002_owner_ownerdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='user_password',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='username',
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_email',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='owner_email'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_password',
            field=models.CharField(default='', max_length=50, verbose_name='owner_password'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_username',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='owner_username'),
        ),
    ]
