# Generated by Django 3.0.8 on 2021-01-14 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kouponbank', '0003_delete_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_capacity', models.IntegerField(default=0)),
                ('table_outlet', models.BooleanField(default=False)),
                ('table_near_wall', models.BooleanField(default=False)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_table', to='kouponbank.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('times', models.CharField(max_length=48)),
                ('date', models.DateField()),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_timeslot', to='kouponbank.Table')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_reservation', to='kouponbank.Business')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_reservation', to='kouponbank.Table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reservation', to='kouponbank.User')),
            ],
        ),
    ]
